name: navihub
debug: env("APP_DEBUG", true)
url: env("APP_URL", "http://127.0.0.1")

servers:
  http:
    port: env("PORT", "3000")

log:
  path: env("LOG_PATH", "")
  level: env("LOG_LEVEL", "info")
  formatter: env("LOG_FORMATTER", "text")

gaode:
  name: env("GAODE_NAME", "web_tianqi")
  key: env("GAODE_KEY", "e89b19ce8c8780ab0dfddad9f7811848")
